jruby-gradle/jruby-gradle-plugin

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/integTest/groovy/com/github/jrubygradle/JRubyGenerateGradleRbIntegrationSpec.groovy, src/integTest/groovy/com/github/jrubygradle/JRubyPrepareGemsIntegrationSpec.groovy, src/main/groovy/com/github/jrubygradle/GenerateGradleRb.groovy, src/main/groovy/com/github/jrubygradle/JRubyPlugin.groovy, src/main/resources/META-INF/gradle-plugins/rubystub.template
This feature needs more testing and is currently marked as incubating since it'll probably be in flux for a couple releases
=> Generate gradle.rb

src/integTest/groovy/com/github/jrubygradle/JRubyPrepareGemsIntegrationSpec.groovy, src/main/groovy/com/github/jrubygradle/GemUtils.groovy
this is the first towards using jruby-mains but valid as such since it allows to create jar files with embedded gems (used by org.jruby.ScriptingContainer or javax.scripting) on all environments (OSGi, J2EE, etc) - for jruby-1.7.x you need to add ```uri:classloader://``` to LOAD_PATH - on jruby-9k it is already default.
=> generate .jrubydir files for installed gems

build.gradle, src/main/groovy/com/github/jrubygradle/GemUtils.groovy, src/main/groovy/com/github/jrubygradle/internal/JRubyExecUtils.groovy, src/test/groovy/com/github/jrubygradle/internal/JRubyExecUtilsSpec.groovy
- Fixed an issue with creating .jrubydir entries for jruby < 1.7.19. Solution is to not create them for now and log a warning. 
- Upgraded Spock to 1.0
=>  Resolved issues port #108 merge

src/main/groovy/com/github/jrubygradle/internal/GemVersion.groovy, src/test/groovy/com/github/jrubygradle/internal/GemVersionSpec.groovy
* maven open ranges [1.2,) will be converted to [1.2,99999) to allow numerical comparison
* the intersection of [0,) and [4.0, 4.5] worked only in one direction
=> fixes two problems with the GemVersion

jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/JRubyExecUtils.groovy, jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/internal/JRubyExecUtilsSpec.groovy
=> handle 9.0.0.0.rc1 and 9.0.0.0 jruby versions conversion correctly

jruby-gradle-jar-plugin/build.gradle, jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy
jruby-mains moved to the jruby organization, i.e. it has a different
maven coordinate as well different java package names
=> use jruby-mains-0.4.0

jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/GemVersion.groovy, jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/internal/GemVersionSpec.groovy
gradle can not resolve 1.0.4.0 to 1.0.4 the same way maven does. removing the tailing
'0' helps to be more in line with maven.
fixes #213
=> remove trailing 0 version parts on ranges

jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy
When using a member variable that is named the same as a property, the behavior
from subclassing can be very confusing
Take the following example:
```groovy
class Parent {
protected String configuration = "foo"
String getConfiguration() {
return configuration
}
void doSomething() {
logger.info("Parent using ${configuration}")
}
}
class Child {
String getConfiguration() {
return 'hello'
}
void doSomething() {
logger.info("Child using ${configuration}")
super.doSomething()
}
}
```
Invoking childInstance.doSomething() will output:
Child using hello
Parent using foo
This can be remedied (pointed out by @ysb33r) by calling `this.@configuration`
which will force a property lookup in Groovy. I personally find it less
error-prone to keep member names ddifferent from the proprty names which expose …
=> Avoid member vs. property name collisions in JRubyJar

.travis.yml
=> Remove oraclejdk7 from test matrix and reduce redundant task execution

jruby-gradle-base-plugin/build.gradle, jruby-gradle-jar-plugin/gradle/integration-test.gradle
IMO 2.4 is no longer worth testing specifically for
=> Restrict gradleTest to 2.0, 2.2 and 2.6

jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/internal/JRubyDirInfo.groovy
This will allow the dirinfo directory to be used as a staging ground but as
@mkristian correctly points out, this means the dirinfo directory will get more
and more stale/inaccurate as time goes on. This necessitates a refactored
approach to generating the .jrubydir files and injecting them into the packed
jar file
Fixes #220
=> Prevent new instantiations of JRubyDirInfo from deleting the dirinfo

docs/errors/jar-deprecated-jrubyversion.adoc, jruby-gradle-jar-plugin/src/integTest/groovy/com/github/jrubygradle/jar/JRubyJarIntegrationSpec.groovy, jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJarPlugin.groovy, jruby-gradle-jar-plugin/src/test/groovy/com/github/jrubygradle/jar/JRubyJarPluginSpec.groovy
This should *help* prevent users from hurting themelves, I hope
Fixes #191
=> Add a warning message if a JRubyJar user uses an old old version of JRuby

jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/GemUtils.groovy, jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/GemUtilsSpec.groovy
instead using an Overwrite strategy either create the file if it is not
there or compare the old content with new content and write out the
file if something changed.
fixes #229
=> make sure the generated Jars.lock file matches the installed jars

build.gradle, examples/self-executing-jar/build.gradle, jruby-gradle-base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyPrepareGemsIntegrationSpec.groovy, jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/GemUtils.groovy, jruby-gradle-jar-plugin/build.gradle, jruby-gradle-jar-plugin/gradle/integration-test.gradle, jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy, jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/internal/JRubyDirInfoTransformer.groovy, jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/internal/JRubyJarCopyAction.groovy
The bug fixes to ensure `.jrubydir` generation gets corrected (see also jruby-gradle/jruby-gradle-storm-plugin#24) is (in my opinion) important enough to warrant getting out in a patch release while we shore up the 1.2.0 release.
=> Candidate fixes for 1.1.4

jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy, jruby-gradle-jar-plugin/src/test/groovy/com/github/jrubygradle/jar/JRubyJarPluginSpec.groovy
Currently adding manifest attributes is impossible when the `Main-Class` is provided. This means it's only possible in non-runnable jars. Which pretty much makes `Class-Path` manifest attribute unusable.
I've added a spec that showcases the issue. I've also added a fix that works for me. But would best be reviewed since it rewrites a fix made in https://github.com/jruby-gradle/jruby-gradle-plugin/commit/eedfe8237253594da517fb77437976f7611d59b0
=> Allow manifest attributes to coexist with Main-Class

jruby-gradle-jar-plugin/src/integTest/groovy/com/github/jrubygradle/jar/JRubyJarIntegrationSpec.groovy, jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy
This is a rework of #271, with an accompanying test, which I believe meets @wenhoujx's needs
=> Allow JRubJar jar-dependencies to be upgraded

jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/GemUtils.groovy
I am trying to get capybara webkit to install in jruby-gradle (on Windows). I am slowly getting there. This has been possible in JRuby for a few weeks now since the `mkmf` module (MakeMakefile) has been introduced. But I encountered two problems in jruby-gradle and I have fixes for them...
* The first is to get rid of the call to `setEnvironment`. With the code in master I get this error:
```
'java' is not recognized as an internal or external command, operable program or batch file.
```
... `setEnvironment` appears to remove existing environment variables instead of just adding the two new ones. By using the alternative `environment` function I was able to fix this.
* The second one is a bit more tricky. Using `GEM_HOME=/some/directory gem install` appears to differ from `gem install …
=> Mkmf compatibility

jruby-gradle-war-plugin/src/main/groovy/com/github/jrubygradle/war/JRubyWar.groovy
Changed 
`org.jruby.rack:jruby:rack`
to 
`org.jruby.rack:jruby-rack`
so that it can resolve
Fix for Issue #276
=> Resolve jruby-rack dependancy

jruby-gradle-base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyExecExtensionIntegrationSpec.groovy, jruby-gradle-base-plugin/src/integTest/resources/scripts/envVars.rb, jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/JRubyExecDelegate.groovy, jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/internal/JRubyExecDelegateSpec.groovy
This fixes two problems:
1. That JRubyExecDelegate was not passing on environment variables to `javaexec`. It was replacing them with `System.env`.
2. That certain overloaded versions of the `environment()` method were not being properly looked up by just doing `"${k}" v`. It was replaced with `invokeMethod` and now seems to look up the method correctly for different cases.
The following integration tests were already failing before I made any changes:
```
com.github.jrubygradle.JRubyExecIntegrationSpec > Running a script that requires a gem using custom embedded rubygems-servlets maven repo FAILED
com.github.jrubygradle.JRubyPrepareGemsIntegrationSpec > Check if rack version gets resolved FAILED
com.github.jrubygradle.JRubyPrepareGemsIntegrationSpec > Check if prerelease gem gets …
```
=> Fixes #293 - Environment Variables not Passes to javaexec

jruby-gradle-jar-plugin/build.gradle, jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy
fixes an issue with puma and `Bundler`. puma checks for `defined?Bunder` and the old jruby-mains did define it even if bundler was not used at all. this of course confuses puma.
=> switch to latest jruby-mains version

.travis.yml, appveyor.yml, build.gradle, gradle.properties
This small PR configures the `build-scan` Gradle plugin (https://guides.gradle.org/creating-build-scans/) which yields further insight into the build, allowing the team to make informed decisions on where and when the build may be tweaked to get faster, more performant builds.
=> Configure build-scan plugin

jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/internal/JRubyJarCopyAction.groovy
Use `WorkResults.didWork()` instead of deprecated `SimpleWorkResult`.
Only caveat: `WorkResults.didWork()` first appeared in Gradle 4.2. Making this the minimum required version.
=> use WorkResults.didWork() instead of deprecated SimpleWorkResult

jar-plugin/build.gradle, jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy, jar-plugin/src/main/groovy/com/github/jrubygradle/jar/internal/JRubyDirInfoTransformer.groovy, jar-plugin/src/main/groovy/com/github/jrubygradle/jar/internal/JRubyJarCopyAction.groovy
Unfortunately as of v4.0.4, the shadow plugin for Gradle still explodes all the nested `.jar` files rather than injecting them into the shadow file properly, so `JRubyJarCopyAction` is still needed.
This pull request effectively syncs our tree with 4.0.4 and puts us on good footing for the future.
Closes #307
=> Sync JRubyJarCopyAction with the upstream/originating shadow code

base-plugin/src/main/groovy/com/github/jrubygradle/JRubyExec.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPrepare.groovy
Simple change, but getters/properties in tasks should all be annotated.
=> Annotate task properties

core-plugin/src/integTest/groovy/com/github/jrubygradle/api/core/IvyXmlProxyServerIntegrationSpec.groovy, core-plugin/src/main/groovy/com/github/jrubygradle/api/core/JRubyCorePlugin.groovy, core-plugin/src/main/groovy/com/github/jrubygradle/api/core/RepositoryHandlerExtension.groovy, core-plugin/src/main/groovy/com/github/jrubygradle/api/gems/GemResolverStrategy.groovy, core-plugin/src/main/groovy/com/github/jrubygradle/internal/gems/GemVersionResolver.groovy
Sometimes it is convenient to not use the Bundler-like strategy from GemVersionResolver, especially in the cases of pre-releases.
This PR depends on #373 being merged first.
=> Allow script author to bypass Bundler-like strategy for resolving dependencies

base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyPrepareGemsIntegrationSpec.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/GenerateGradleRb.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/JRubyExec.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPlugin.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPrepare.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/internal/JRubyExecDelegate.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/internal/JRubyExecUtils.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/internal/JRubyPrepareUtils.groovy, build.gradle, core-plugin/src/main/groovy/com/github/jrubygradle/api/core/AbstractJRubyPrepare.groovy, core-plugin/src/main/groovy/com/github/jrubygradle/api/core/JRubyCorePlugin.groovy, core-plugin/src/main/groovy/com/github/jrubygradle/api/core/RepositoryHandlerExtension.groovy, core-plugin/src/main/groovy/com/github/jrubygradle/api/gems/GemResolverStrategy.groovy, core-plugin/src/main/groovy/com/github/jrubygradle/api/gems/GemUtils.groovy, core-plugin/src/test/groovy/com/github/jrubygradle/api/gems/GemUtilsSpec.groovy, gradle.properties, jar-plugin/src/integTest/groovy/com/github/jrubygradle/jar/JRubyJarTestKitSpec.groovy
- Use the new 1.0.0-alpha.1 Grolifant release that has configuration-cache
safety built-in.
- Check that no usage of `Project` object will be done after configuration
phase has ended.
- Maintain compatibility down to Gradle 4.3.
=> Prepare for Gradle's configuration cache

base-plugin/src/main/groovy/com/github/jrubygradle/GenerateGradleRb.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/JRubyExec.groovy, build.gradle, core-plugin/src/main/groovy/com/github/jrubygradle/api/core/AbstractJRubyPrepare.groovy
This PR fixes some validation problems with tasks in the plugin that will cause any build using the plugin to fail with Gradle 7.0. It also enables strict validation during the build, so any new validation problems introduced will make the build fail.
The particular problems fixed by this PR are:
```text
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':jruby-gradle-core-plugin:validateTaskProperties'.
> Task property validation failed. See https://docs.gradle.org/5.4.1/userguide/more_about_tasks.html#sec:task_input_output_annotations for more information on how to annotate task properties.
> Warning: Task type 'com.github.jrubygradle.api.core.AbstractJRubyPrepare': property 'projectOperations' is not annotated with an input or output annotation. …
```
=> Fix task property annotation problems

base-plugin/src/main/groovy/com/github/jrubygradle/GenerateGradleRb.groovy, base-plugin/src/main/groovy/com/github/jrubygradle/JRubyExec.groovy, build.gradle, core-plugin/src/main/groovy/com/github/jrubygradle/api/core/AbstractJRubyPrepare.groovy
Backport of https://github.com/jruby-gradle/jruby-gradle-plugin/pull/418.
This PR fixes some validation problems with tasks in the plugin that will cause any build using the plugin to fail with Gradle 7.0. It also enables strict validation during the build, so any new validation problems introduced will make the build fail.
The particular problems fixed by this PR are:
```text
* What went wrong:
Execution failed for task ':jruby-gradle-plugin:validateTaskProperties'.
> Task property validation failed. See https://docs.gradle.org/5.4.1/userguide/more_about_tasks.html#sec:task_input_output_annotations for more information on how to annotate task properties.
> Warning: Task type 'com.github.jrubygradle.GenerateGradleRb': property 'destinationDir' is not annotated with an input or output …
```
=> Fix task property annotation problems for 2.0

core-plugin/src/main/groovy/com/github/jrubygradle/api/gems/GemUtils.groovy
This should remove the deprecation warning and fix #427 .
=> Use new `mainClass` property instead of `main`
