src/main/groovy/com/github/jrubygradle/GemUtils.groovy

there is no sane way to provide an test case for this. at least I would not know how

some little improvements on calling gem install

---

build.gradle
src/integTest/groovy/com/github/jrubygradle/JRubyPrepareJarsIntegrationSpec.groovy
src/main/groovy/com/github/jrubygradle/GemUtils.groovy
src/main/groovy/com/github/jrubygradle/JRubyPlugin.groovy
src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy
src/main/groovy/com/github/jrubygradle/JRubyPrepareJars.groovy

towards using jruby-mains and a more uniform way of running jruby (standalone or from a jar or from a war)
there are still loose ends here

WIP Jruby jar dependencies

---

build.gradle
src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy

Look at that changelog!
<http://jruby.org/2015/05/05/jruby-1-7-20.html>

Update to defaulting to JRuby 1.7.20

---

.travis.yml
appveyor.yml
build.gradle
src/gradleTest/jrubyExec/build.gradle
src/gradleTest/jrubyExec/scripts/requiresGem.rb
src/integTest/groovy/com/github/jrubygradle/JRubyGenerateGradleRbIntegrationSpec.groovy

- Adds gradleTest compatibility testing. I've adde done test to exercise JRubyExec. It should be sufficient for most cases.
- Also disabled the Windows test from GradleRb. We need to fix this, but I would rather have the build passing as it might be masking other more serious issues under Windows, especially with R9000 coming up.

gradleTest + more

---

.travis.yml
build.gradle
gradle.properties
jruby-gradle-base-plugin/build.gradle
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy
jruby-gradle-jar-plugin/build.gradle
jruby-gradle-jar-plugin/src/test/groovy/com/github/jrubygradle/jar/JRubyJarPluginSpec.groovy

See this for more details: <http://jruby.org/2015/07/07/jruby-1-7-21.html>

Upgrade our default to JRuby 1.7.21

---

jruby-gradle-base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyPrepareGemsIntegrationSpec.groovy
jruby-gradle-base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyPrepareJarsIntegrationSpec.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPlugin.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPrepare.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPrepareGems.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPrepareJars.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/JRubyPluginTest.groovy

this is basically the fix for #141

Jruby prepare jars

---

gradle.properties
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy

Change our default version to JRuby 9k

---

README.adoc
docs/community.adoc
docs/download.adoc
docs/errors/jrubyjar-version-conflict.adoc
jruby-gradle-base-plugin/build.gradle
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyExec.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/JRubyExecSpec.groovy
jruby-gradle-jar-plugin/build.gradle
jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy
jruby-gradle-jar-plugin/src/test/groovy/com/github/jrubygradle/jar/JRubyJarPluginSpec.groovy
jruby-gradle-jar-plugin/src/test/groovy/com/github/jrubygradle/jar/JRubyJarSpec.groovy

Properly overwrite the jrubyMains and jrubyVersion

---

jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/JRubyPluginExtensionSpec.groovy
jruby-gradle-jar-plugin/gradle/integration-test.gradle
jruby-gradle-jar-plugin/src/integTest/groovy/com/github/jrubygradle/jar/JRubyJarIntegrationSpec.groovy
jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy
jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/internal/JRubyDirInfo.groovy
jruby-gradle-jar-plugin/src/test/groovy/com/github/jrubygradle/jar/JRubyJarPluginSpec.groovy
jruby-gradle-jar-plugin/src/test/groovy/com/github/jrubygradle/jar/JRubyJarSpec.groovy

This pull request also includes modifications to how JRubyJar works for its reliance on `defaultVersion`

Add version change callbacks for jruby.defaultVersion and jruby.execVersion

---

CODE_OF_CONDUCT.adoc

This seems reasonable enough
Fixes #173

Add a of conduct  from contributor-covenant.org

---

.travis.yml
gradle.properties
jruby-gradle-base-plugin/build.gradle
jruby-gradle-base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyExecExtensionIntegrationSpec.groovy
jruby-gradle-base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyExecIntegrationSpec.groovy
jruby-gradle-base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyPrepareGemsIntegrationSpec.groovy
jruby-gradle-base-plugin/src/integTest/resources/scripts/require-a-gem.rb
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPlugin.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/RubygemsServlet.java

getting the server configured and started and stopped.

[WIP] embed rubygems-servlet into gradle

---

gradle.properties
jruby-gradle-base-plugin/README.adoc
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy
jruby-gradle-jar-plugin/src/integTest/groovy/com/github/jrubygradle/jar/JRubyJarIntegrationSpec.groovy

See: <http://jruby.org/2015/09/02/jruby-9-0-1-0.html>
Fixes #211

Upgrade the default version of JRuby to 9.0.1.0

---

build.gradle
jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy

Reluctantly submitting without an automated test, it's just so simple :(
Fixes #200

Exclude the entire gems/cache directory when packing the jar

---

build.gradle
jruby-gradle-base-plugin/README.adoc
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPlugin.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/JRubyPluginSpec.groovy

Provide a command-line override for the default JRuby version

---

gradle.properties
gradle/integration-tests.gradle
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyExec.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/JRubyExecTraits.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/JRubyExecSpec.groovy
jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy
jruby-gradle-jar-plugin/src/test/groovy/com/github/jrubygradle/jar/JRubyJarSpec.groovy

While I figure out how to handle `.jrubydir` I figured I'd fix some little things

Picking up some low-hanging fruit

---

jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy

Add bin/** to staged files to be included in the jar. Resolves #245

---

jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy
jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy

These are some changes cherry-picked from master to get a minor bugfix release out.

1.1.3 release candidate

---

gradle.properties
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy

See also: <http://jruby.org/2015/10/21/jruby-9-0-3-0.html>
Fixes #255

Upgrade the default JRuby to 9.0.3.0

---

gradle.properties
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy

See also: <http://jruby.org/2015/11/13/jruby-9-0-4-0.html>

Upgrade the default base to 9.0.4.0

---

gradle.properties
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy

See also: <http://jruby.org/2015/11/13/jruby-9-0-4-0.html>
Now with more JRuby

1.1.5 release candidate

---

gradle.properties
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy

See also: <http://jruby.org/2016/01/26/jruby-9-0-5-0.html>

Bump the base version of JRuby to 9.0.5.0

---

.travis.yml
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/GemVersion.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/internal/GemVersionSpec.groovy

Fix range check for string versions

---

jruby-gradle-base-plugin/README.adoc

* change gems to dependencies
* change configuration to configurations

Fix example for extending JRubyPrepare task

---

CHANGELOG.md

#262
> Honestly, manually keeping a changelog is too tedious for me 😄
>
> I do try to keep track of things in [milestones]()
I can appreciate not wanting to update/maintain the CHANGELOG file. I think that's fine if we end it with a note suggesting where to look instead. What do you think?

Document that the CHANGELOG is no longer maintained

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
jruby-gradle-base-plugin/build.gradle
jruby-gradle-base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyExecIntegrationSpec.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/GemUtils.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyExec.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/JRubyExecUtils.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/JRubyExecSpec.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/JRubyPluginExtensionSpec.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/JRubyPluginSpec.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/internal/JRubyExecUtilsSpec.groovy

http://jruby.org/2017/11/08/jruby-9-1-14-0.html

Default to JRuby 9.1.14.0 which now has some nice Java 9 support :clap:

---

jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/GemVersion.groovy
jruby-gradle-base-plugin/src/test/groovy/com/github/jrubygradle/internal/GemVersionSpec.groovy

use workaround an upstream bug in version range

---

jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/GemVersionResolver.groovy

We were starting to use this plugin and ran into the same issue identified in PR #327.
Since the feedback has never been incorporated in that PR, this should be what is needed to get this going again.
Also IDEA decided to alphabetize the imports and CodeNarc didn't like having the repetitive debug lines.

Fixing the "Cannot change strategy" issue.

---

jruby-gradle-base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyPrepareGemsIntegrationSpec.groovy
jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/GemUtils.groovy

See the stream of consciousness in #341 :smile:

Handle dependencies which are needed at installation time

---

jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy
jar-plugin/src/test/groovy/com/github/jrubygradle/jar/JRubyJarSpec.groovy

Place the jrubyjar and prepareJrubyJar in the right group

---

base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyPrepareGemsIntegrationSpec.groovy
core-plugin/src/main/groovy/com/github/jrubygradle/api/gems/GemVersion.groovy
core-plugin/src/test/groovy/com/github/jrubygradle/api/gems/GemVersionSpec.groovy

resolves #394 fix gem requirements resolution

---

base-plugin/src/integTest/groovy/com/github/jrubygradle/JRubyGenerateGradleRbIntegrationSpec.groovy
base-plugin/src/main/groovy/com/github/jrubygradle/JRubyPluginExtension.groovy
base-plugin/src/main/groovy/com/github/jrubygradle/internal/JRubyExecUtils.groovy
base-plugin/src/test/groovy/com/github/jrubygradle/internal/JRubyExecUtilsSpec.groovy
build.gradle
core-plugin/src/main/groovy/com/github/jrubygradle/api/core/AbstractJRubyPrepare.groovy
core-plugin/src/main/groovy/com/github/jrubygradle/internal/core/AbstractIvyXmlProxyServer.groovy
core-plugin/src/test/groovy/com/github/jrubygradle/api/core/RubyGemQueryRestApiSpec.groovy
examples/run-simple-ruby-script/build.gradle
gradle.properties
jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy
jar-plugin/src/main/groovy/com/github/jrubygradle/jar/internal/JRubyJarCopyAction.groovy

This takes into account a couple of changes Grolifant 1.x.

Upgrade to grolifant 1.0.0-alpha.4
